FROM node:10.19.0

RUN mkdir app
WORKDIR /app
COPY . /app
RUN npm install
COPY ./while.sh /tmp/

RUN npm run build
RUN apt update
RUN apt install postgresql -y

EXPOSE 3000
EXPOSE 5555
#CMD ["bash", "/tmp/while.sh"]
CMD cd dist && node main.js
