version: '3.8'
services:
  database:
    image: postgres:13.3
    volumes:
      - '/var/lib/postgresql/data'
    env_file:
      - ./.postgres.env
    restart: unless-stopped
    ports:
      - '5432:5432'
